# Using CodeClimate Platform
# http://docs.codeclimate.com/article/300-the-codeclimate-platform

engines:
  rubocop:
    enabled: true
  scsslint:
    enabled: true
  bundler_audit:
    enabled: true

ratings:
  paths:
  - app/**/*
  - lib/**/*
  - "**/*.rb"

exclude_paths:
- db/schema.rb
- spec/**/*
- vendor/**/*
